# Generated by Django 4.1.9 on 2023-05-15 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("localizacao", models.CharField(max_length=255, unique=True)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        choices=[
                            ("audi", "Audi"),
                            ("bmw", "BMW"),
                            ("ford", "Ford"),
                            ("honda", "Honda"),
                            ("mercedes", "Mercedes-Benz"),
                            ("nissan", "Nissan"),
                            ("toyota", "Toyota"),
                            ("volkswagen", "Volkswagen"),
                        ],
                        max_length=50,
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("cor", models.CharField(max_length=50)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                ("disponibilidade", models.BooleanField(default=True)),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.loja"
                    ),
                ),
            ],
        ),
    ]
