# Generated by Django 4.1.9 on 2023-05-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carro",
            name="locacao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="carro",
            name="venda",
            field=models.BooleanField(default=False),
        ),
    ]
