# Generated by Django 4.1.9 on 2023-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_carro_locacao_carro_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="carro",
            name="placa",
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
