# Generated by Django 4.1.9 on 2023-05-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_funcionario",
            field=models.BooleanField(default=False),
        ),
    ]
