# Generated by Django 4.1.9 on 2023-05-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_customuser_is_funcionario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_cliente",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_funcionario",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CLIENTE", "Cliente"),
                    ("FUNCIONARIO", "Funcionario"),
                ],
                default="ADMIN",
                max_length=50,
            ),
        ),
    ]
