# Generated by Django 4.1.9 on 2023-05-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_remove_customuser_is_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CLIENTE", "Cliente"),
                    ("FUNCIONARIO", "Funcionario"),
                ],
                max_length=50,
            ),
        ),
    ]
