# Generated by Django 4.1.9 on 2023-05-16 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("usuarios", "0006_funcionarioprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionarioprofile",
            name="loja",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.loja",
            ),
            preserve_default=False,
        ),
    ]
