# Generated by Django 4.1.9 on 2023-05-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("usuarios", "0007_funcionarioprofile_loja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionarioprofile",
            name="loja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.loja"
            ),
        ),
    ]
