# Generated by Django 4.1.9 on 2023-05-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_carro_locacao_carro_venda"),
        ("locadora", "0002_aluguel"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluguel",
            name="carro",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.carro",
            ),
            preserve_default=False,
        ),
    ]
