# Generated by Django 4.1.9 on 2023-05-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_carro_locacao_carro_venda"),
        ("locadora", "0003_aluguel_carro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluguel",
            name="loja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.loja",
            ),
        ),
    ]
