# Generated by Django 4.1.9 on 2023-05-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_carro_locacao_carro_venda"),
        ("locadora", "0004_alter_aluguel_loja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluguel",
            name="loja",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.loja",
            ),
            preserve_default=False,
        ),
    ]
